Fixing IndexError in keypress_end function
When using the keypress_end function to move to the top of an empty list of tasks (i.e. len(self.body)==0), the application crashes displaying "IndexError: Can't set focus, ListBox is empty". This commit adds an if statement to the keypress_end function that checks if self.body's length is greater than 0.

This error can be replicated on version 2.2.0 by having an empty task list and pressing the "G" key. 


Traceback for reference:

Traceback (most recent call last):
  File "~/.local/bin/vit", line 8, in <module>
    sys.exit(main())
  File "~/.local/lib/python3.8/site-packages/vit/command_line.py", line 5, in main
    Application(options, filters)
  File "~/.local/lib/python3.8/site-packages/vit/application.py", line 78, in __init__
    self.loop.run()
  File "~/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "~/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "~/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "~/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 827, in _loop
    self._watch_files[fd]()
  File "~/.local/lib/python3.8/site-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "~/.local/lib/python3.8/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "~/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "~/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "~/.local/lib/python3.8/site-packages/urwid/wimp.py", line 651, in keypress
    return self._current_widget.keypress(size, key)
  File "~/.local/lib/python3.8/site-packages/vit/application.py", line 68, in keypress
    return super().keypress(size, key)
  File "~/.local/lib/python3.8/site-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "~/.local/lib/python3.8/site-packages/vit/base_list_box.py", line 115, in keypress
    if self.action_manager_registrar.execute_handler(keys, size):
  File "~/.local/lib/python3.8/site-packages/vit/action_manager.py", line 24, in execute_handler
    handled_action['callback'](*args)
  File "~/.local/lib/python3.8/site-packages/vit/task_list.py", line 506, in keypress_end
    super().keypress_end(size)
  File "~/.local/lib/python3.8/site-packages/vit/base_list_box.py", line 77, in keypress_end
    self.set_focus(len(self.body) - 1)
  File "~/.local/lib/python3.8/site-packages/urwid/listbox.py", line 547, in set_focus
    raise IndexError("Can't set focus, ListBox is empty")
IndexError: Can't set focus, ListBox is empty